export const ActionTypes = {
  SET_PRODUCT: 'SET_PRODUCT',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  SET_SEARCH_PRODUCT: 'SET_SEARCH_PRODUCT',
  ADJUST_ITEM_QTY: 'ADJUST_ITEM_QTY',
  SET_FILTER: 'SET_FILTER',
  SET_FILTER_P: 'SET_FILTER_P',
};
